//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Audio
    {
        public const string BundleName = "audio";
        public const string FX_BLOWPIPE = "fx_blowpipe";
        public const string FX_BOSS1_ATK3 = "fx_boss1_atk3";
        public const string FX_BOW_DRAW = "fx_bow_draw";
        public const string FX_BOW_SHOOT = "fx_bow_shoot";
        public const string FX_BOX_HIT = "fx_box_hit";
        public const string FX_BTN = "fx_btn";
        public const string FX_BTN_LEVELUP = "fx_btn_levelup";
        public const string FX_BTN_START = "fx_btn_start";
        public const string FX_BUY = "fx_buy";
        public const string FX_CHEST_OPEN = "fx_chest_open";
        public const string FX_COIN = "fx_coin";
        public const string FX_DOOR = "fx_door";
        public const string FX_ENERGY = "fx_energy";
        public const string FX_EXPLODE_BIG = "fx_explode_big";
        public const string FX_EXPLODE_SMALL = "fx_explode_small";
        public const string FX_GUN_1 = "fx_gun_1";
        public const string FX_GUN_2 = "fx_gun_2";
        public const string FX_GUN_3 = "fx_gun_3";
        public const string FX_GUN_4 = "fx_gun_4";
        public const string FX_GUN_5 = "fx_gun_5";
        public const string FX_GUN_6 = "fx_gun_6";
        public const string FX_GUN_7 = "fx_gun_7";
        public const string FX_GUN_8 = "fx_gun_8";
        public const string FX_GUN_ROCKET = "fx_gun_rocket";
        public const string FX_HEALTHPOT = "fx_healthpot";
        public const string FX_HIT = "fx_hit";
        public const string FX_HIT_P1 = "fx_hit_p1";
        public const string FX_SHOOT_E1 = "fx_shoot_e1";
        public const string FX_SHORT_FART = "fx_short_fart";
        public const string FX_SHOW_UP = "fx_show_up";
        public const string FX_SKILL_C1 = "fx_skill_c1";
        public const string FX_SKILL_C2 = "fx_skill_c2";
        public const string FX_SPIKE = "fx_spike";
        public const string FX_SWITCH = "fx_switch";
        public const string FX_SWORD = "fx_sword";
        public const string FX_TRANSFORM = "fx_transform";
        public const string FX_WOLF_ATK = "fx_wolf_atk";
        public const string FX_WOLF_GROWL = "fx_wolf_growl";
        public const string FX_WOLF_SHOW = "fx_wolf_show";
        public const string HUMAN1_HURT2 = "human1 hurt2";
        public const string HUMAN2_HURT2 = "human2 hurt2";
        public const string BGM_1LOW = "bgm_1Low";
        public const string BGM_BOSS = "bgm_boss";
        public const string BGM_ROOM = "bgm_room";
        public const string SF_WOLF_HOWL = "sf_wolf_howl";
    }
    public class Common
    {
        public const string BundleName = "common";
        public const string LIGHT = "light";
    }
    public class Uibossfight_prefab
    {
        public const string BundleName = "uibossfight_prefab";
        public const string UIBOSSFIGHT = "UIBossFight";
    }
    public class Uiendpanel_prefab
    {
        public const string BundleName = "uiendpanel_prefab";
        public const string UIENDPANEL = "UIEndPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uiloadingpanel_prefab
    {
        public const string BundleName = "uiloadingpanel_prefab";
        public const string UILOADINGPANEL = "UILoadingPanel";
    }
    public class Uimobilecontrolpanel_prefab
    {
        public const string BundleName = "uimobilecontrolpanel_prefab";
        public const string UIMOBILECONTROLPANEL = "UIMobileControlPanel";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
    }
    public class Uisettingspanel_prefab
    {
        public const string BundleName = "uisettingspanel_prefab";
        public const string UISETTINGSPANEL = "UISettingsPanel";
    }
    public class Uistartmenupanel_prefab
    {
        public const string BundleName = "uistartmenupanel_prefab";
        public const string UISTARTMENUPANEL = "UIStartMenuPanel";
    }
}
