//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Audio
    {
        public const string BundleName = "audio";
        public const string FX_BOX_HIT = "fx_box_hit";
        public const string FX_BTN = "fx_btn";
        public const string FX_BTN_LEVELUP = "fx_btn_levelup";
        public const string FX_BTN_START = "fx_btn_start";
        public const string FX_BUY = "fx_buy";
        public const string FX_CHEST_OPEN = "fx_chest_open";
        public const string FX_COIN = "fx_coin";
        public const string FX_DOOR = "fx_door";
        public const string FX_ENERGY = "fx_energy";
        public const string FX_GUN_1 = "fx_gun_1";
        public const string FX_GUN_2 = "fx_gun_2";
        public const string FX_GUN_3 = "fx_gun_3";
        public const string FX_GUN_4 = "fx_gun_4";
        public const string FX_GUN_5 = "fx_gun_5";
        public const string FX_GUN_6 = "fx_gun_6";
        public const string FX_GUN_7 = "fx_gun_7";
        public const string FX_GUN_8 = "fx_gun_8";
        public const string FX_HIT = "fx_hit";
        public const string FX_HIT_P1 = "fx_hit_p1";
        public const string FX_SHOOT_E1 = "fx_shoot_e1";
        public const string FX_SHOW_UP = "fx_show_up";
        public const string FX_SKILL_C1 = "fx_skill_c1";
        public const string FX_SPIKE = "fx_spike";
        public const string FX_SWITCH = "fx_switch";
        public const string FX_SWORD = "fx_sword";
        public const string FX_TRANSFORM = "fx_transform";
        public const string HUMAN1_HURT2 = "human1 hurt2";
        public const string HUMAN2_HURT2 = "human2 hurt2";
        public const string BGM_FASTER = "bgm_Faster";
        public const string BGM_GRASSWALK = "bgm_Grasswalk";
        public const string BGM_LOON = "bgm_loon";
        public const string BGM_WINMUSIC = "bgm_winmusic";
        public const string BUTTONCLICK = "buttonclick";
        public const string DAVEHURT1 = "DaveHurt1";
        public const string DAVEHURT2 = "DaveHurt2";
        public const string FINALWAVE = "finalwave";
        public const string HUGEWAVE = "hugewave";
        public const string PAUSE = "pause";
        public const string PLANT = "plant";
        public const string PLANT2 = "plant2";
        public const string POINTS = "points";
        public const string PRIZE = "prize";
        public const string PRODUCESUN = "ProduceSun";
        public const string READYSETPLANT = "readysetplant";
        public const string SEEDLIFT = "seedlift";
        public const string SIREN = "siren";
        public const string SWING = "swing";
        public const string TAP = "tap";
        public const string TAP2 = "tap2";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uiinventorypanel_prefab
    {
        public const string BundleName = "uiinventorypanel_prefab";
        public const string UIINVENTORYPANEL = "UIInventoryPanel";
    }
    public class Uimobilecontrolpanel_prefab
    {
        public const string BundleName = "uimobilecontrolpanel_prefab";
        public const string UIMOBILECONTROLPANEL = "UIMobileControlPanel";
    }
    public class Uipvzgamepanel_prefab
    {
        public const string BundleName = "uipvzgamepanel_prefab";
        public const string UIPVZGAMEPANEL = "UIPvzGamePanel";
    }
    public class Uisettingspanel_prefab
    {
        public const string BundleName = "uisettingspanel_prefab";
        public const string UISETTINGSPANEL = "UISettingsPanel";
    }
    public class Uistartmenupanel_prefab
    {
        public const string BundleName = "uistartmenupanel_prefab";
        public const string UISTARTMENUPANEL = "UIStartMenuPanel";
    }
    public class Uitempstartpanel_prefab
    {
        public const string BundleName = "uitempstartpanel_prefab";
        public const string UITEMPSTARTPANEL = "UITempStartPanel";
    }
}
